# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='vision',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='politician',
            name='about',
            field=models.TextField(max_length=1000),
        ),
    ]
