# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('politician', '0002_auto_20170511_2230'),
        ('theme', '0002_auto_20170511_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500, null=True)),
                ('date', models.DateField()),
                ('reference', models.TextField(max_length=1000, null=True)),
                ('image', models.TextField(max_length=1000, null=True)),
                ('politicians', models.ManyToManyField(null=True, to='politician.Politician')),
                ('themes', models.ManyToManyField(null=True, to='theme.Theme')),
            ],
        ),
    ]
