# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
