# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_userthemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='following',
            field=models.BooleanField(default=False),
        ),
    ]
